### ISSUE TITLE
Connection failed

### ISSUE THREAD

**Issue by jhmgbl** [Heckie75/eQ-3-radiator-thermostat#12]
I always get this message, although I successfully paired the thermostat.

**Comment by Heckie75** [comment]
Hi,
Step 1:
first question is if the thermostat works in general. Have you been able to connect and use the thermostat with the official app? Please check this first. 

If the thermostat does NOT work with the app, then the thermostat is probably broken. Actually, i ran into this situation but this there was still warranty and "notebooksbilliger" gave me a new one that works. 

Step 2:
If the app works perfectly then it could be a problem of distance. Please check if the official app also works after you have put your smartphone at the same position as your Raspberry / PC? Do you think that this could be a problem because there are walls between Raspberry and the thermostat or distance is more than 10 meters?

Step 3:
If the app works perfectly and it is not a problem of distance then go ahead and try to pair devices. Actually I am still not 100% sure if pairing (on bluetooth protocol level) is required. Other people found out that the PIN that you must enter in the App is just a feature on application level (not on bluetooth protocol level) in order to prevent users from connection to their neighbours thermostats. 

Nevertheless, when I initially connected my PC with the thermostat, I ran the bluetooth pairing procedure as follows:
1. Open a terminal windows, start bluetoothctl and enter the following
```
# a. enter bluetoothctl
~$ bluetoothctl
[NEW] Controller 80:86:F2:95:4E:C0 heckies-nuc [default]
[NEW] Device 00:13:17:D0:1E:C0 Nokia AD-42W
[NEW] Device 00:02:72:EC:7E:DA Belkin C63

# b. now enter
[bluetooth]# agent on
Agent registered

# c. now enter
[bluetooth]# scan on
Discovery started
[CHG] Controller 80:86:F2:95:4E:C0 Discovering: yes
[NEW] Device 00:1A:22:0A:91:CF CC-RT-BLE
# ...

# d. now enter "trust" with the mac address of the "CC-RT-BLE" thermostat
[bluetooth]# trust 00:1A:22:0A:91:CF
[CHG] Device 00:1A:22:0A:91:CF Trusted: yes
Changing 00:1A:22:0A:91:CF trust succeeded

# e. Now press the big button at the thermostat until the word "PAIR" appeared. 

# f. enter the following
[bluetooth]# pair 00:1A:22:0A:91:CF
Attempting to pair with 00:1A:22:0A:91:CF
[CHG] Device 00:1A:22:0A:91:CF Connected: yes
[CHG] Device 00:1A:22:0A:91:CF UUIDs: 00001800-0000-1000-8000-00805f9b34fb
[CHG] Device 00:1A:22:0A:91:CF UUIDs: 00001801-0000-1000-8000-00805f9b34fb
[CHG] Device 00:1A:22:0A:91:CF UUIDs: 0000180a-0000-1000-8000-00805f9b34fb
[CHG] Device 00:1A:22:0A:91:CF UUIDs: 3e135142-654f-9090-134a-a6ff5bb77046
[CHG] Device 00:1A:22:0A:91:CF UUIDs: 9e5d1e47-5c13-43a0-8635-82ad38a1386f

# g. now quit bluetoothctl by entering 
[CC-RT-BLE]# quit
Agent unregistered
[DEL] Controller 80:86:F2:95:4E:C0 heckies-nuc [default]
```

2. After you have done this step you can check if the thermostat works in general. This can be done by using the gatttool directly. So open a terminal windows and start gatttool and connect to mac address
```
# a. start gatttool in interactive mode for mac address
~$ gatttool -b 00:1A:22:0A:91:CF -I

# b. connect to device
[00:1A:22:0A:91:CF][LE]> connect
Attempting to connect to 00:1A:22:0A:91:CF
Connection successful

# Please watch for a few seconds if connection is stable. If the device disconnects then there is a problem in terms of bluetooth connection, e.g. unstable connection caused by distance, overloaded network, etc. 

# c. Check if the device answers in general. enter the following
[00:1A:22:0A:91:CF][LE]> char-write-req 0411 01
Characteristic value was written successfully

# d. After step c the device must answer automatically with a notification on handle 0x0421 as follows
Notification handle = 0x0421 value: 02 80

# e. enter quit in order to end gatttool
[00:1A:22:0A:91:CF][LE]> quit
``` 

If the notification of step "d" does NOT appear then there is a problem with the thermostat. But then I can't say what the problem is. As mentioned before I had a thermostat that was broken - nevertheless is does not work with the official app, too. 

The reason could be a different firmware/software version. But I don't know how to get this information. Maybe you can give me the output of the following command:
```
$ gatttool -b 00:1A:22:0A:91:CF -I
[00:1A:22:0A:91:CF][LE]> connect
Attempting to connect to 00:1A:22:0A:91:CF
Connection successful
[00:1A:22:0A:91:CF][LE]> characteristics
handle: 0x0110, char properties: 0x02, char value handle: 0x0111, uuid: 00002a00-0000-1000-8000-00805f9b34fb
handle: 0x0120, char properties: 0x02, char value handle: 0x0121, uuid: 00002a01-0000-1000-8000-00805f9b34fb
handle: 0x0130, char properties: 0x02, char value handle: 0x0131, uuid: 00002a02-0000-1000-8000-00805f9b34fb
handle: 0x0140, char properties: 0x08, char value handle: 0x0141, uuid: 00002a03-0000-1000-8000-00805f9b34fb
handle: 0x0150, char properties: 0x02, char value handle: 0x0151, uuid: 00002a04-0000-1000-8000-00805f9b34fb
handle: 0x0210, char properties: 0x22, char value handle: 0x0211, uuid: 00002a05-0000-1000-8000-00805f9b34fb
handle: 0x0310, char properties: 0x02, char value handle: 0x0311, uuid: 00002a29-0000-1000-8000-00805f9b34fb
handle: 0x0320, char properties: 0x02, char value handle: 0x0321, uuid: 00002a24-0000-1000-8000-00805f9b34fb
handle: 0x0410, char properties: 0x0a, char value handle: 0x0411, uuid: 3fa4585a-ce4a-3bad-db4b-b8df8179ea09
handle: 0x0420, char properties: 0x1a, char value handle: 0x0421, uuid: d0e8434d-cd29-0996-af41-6c90f4e0eb2a
handle: 0xff01, char properties: 0x38, char value handle: 0xff02, uuid: e3dd50bf-f7a7-4e99-838e-570a086c666b
handle: 0xff04, char properties: 0x08, char value handle: 0xff05, uuid: 92e86c7a-d961-4091-b74f-2409e72efe36
handle: 0xff06, char properties: 0x02, char value handle: 0xff07, uuid: 347f7608-2e2d-47eb-913b-75d4edc4de3b
```

Good luck! Let me know what the result is.

Best regards,
Martin

**Comment by Heckie75** [comment]
BTW: Does anybody know how to read firmware version? Most likely is that it is part of the following requests:
```

**Comment by JamesT42** [comment]
I think I had the same problem.
After pairing hcitool con always showed a connection, making the device "busy".
I solved it by starting bluetoothctl and then doing disconnect 00:1A:22:XX:XX:XX
