### ISSUE TITLE
Bt like xm-15b or otger

### ISSUE THREAD

**Issue by gembiart** [Heckie75/eQ-3-radiator-thermostat#3]
Hello. I'm just using this script on rpi3 with gatttooll. Works perfectly ;) 
But the range of built in rpi bt is too small. I'm wondering about to connect usb bt class1 (easy)  or xm-15b (not so eeasy for me ) via serial.
My question is. How should commands look like for eq3bt via serial (for xm-15b , of course after sucessfull connect)
Maybe someone will know how to do it?

Thanks advance ;)

**Comment by Heckie75** [comment]
Hi, 

actually I guess that there shouldn't be a difference for the application (here gatttool) in case that xm-15b is supported by a bluetooth stack (probably bluez). But for my ears it sounds to complicated and riskful. Try to google if other people have experience with xm-15b and gatttool. 

If there is no driver available out-of-the-box and if you don't have a soldering iron,  buy a USB class 1 bluetooth dongle that is supported by linux kernel. That's probably much easier. In this case you probably have to change the code a little bit in order to force gatttool to use a specific hci device, e.g.
`gatttool -I --adapter=hci1` (see line 917 where gatttool is called)
Best regards
Martin
