### ISSUE TITLE
gatttool is now deprecated in Bluez

### ISSUE THREAD

**Issue by gtalev** [Heckie75/eQ-3-radiator-thermostat#37]
gatttool is deprecated in Bluez:
https://git.kernel.org/pub/scm/bluetooth/bluez.git/commit/?id=b1eb2c4cd057624312e0412f6c4be000f7fc3617

**Comment by Heckie75** [comment]
Thank for this information. It seems that ```gatttool``` is marked as deprecated since 2017. That's why I hope that it will be part in future. I use Ubuntu 20.04.1 which comes with Bluez 5.53 and ```gatttool``` is still available. 

In case that ```gatttool``` will be removed in future I have a lot of work :-( Almost all scripts that I have written utilize it. I have no idea where to take the time in order to reimplement all these scripts. However, I've played around with [gatt-python](https://github.com/getsenic/gatt-python) today. Of course using Python is far better programming than remote controlling an interactive gatttool-session by using ```expect``` and writing tcl code.
